build:
  nodes:
    php-analysis:
      environment:
        php:
          version: "7.2"
          ini:
            memory_limit: "-1"
      filter:
        paths: ["app/*", "database/factories/*", "database/seeds/*"]
        dependency_paths:
          - bootstrap/
          - config/
          - resources/
          - routes/
          - vendor/
        excluded_paths:
          - "public/"
          - "tests/"
      tests:
        override:
          -
            command: php-scrutinizer-run
            on_node: 1
          -
            command: phpcs-run
            use_website_config: false
            on_node: 2
    js-analysis:
      environment:
        node: v10.14.2
      filter:
        paths:
          - resources/assets/js
        dependency_paths:
          - node_modules/
        excluded_paths:
          - "resources/assets/js/stories/"
          - "resources/assets/js/translations/"
      tests:
        override:
          -
            command: js-scrutinizer-run
            on_node: 1
          -
            command: eslint-run ./resources/assets/js
            on_node: 2

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 777
    runs: 1
