build:
  nodes:
    php-analysis:
      environment:
        php:
          version: "7.2"
          ini:
            memory_limit: "-1"
        variables:
          DB_CONNECTION: "mysql"
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: scrutinizer
          DB_USERNAME: root
          DB_PASSWORD:
      tests:
        stop_on_failure: true
        override:
          -
            command: php-scrutinizer-run
            on_node: 1
          -
            command: phpcs-run
            use_website_config: false
            on_node: 2
    js-analysis:
      environment:
        node: v10.14.2
      tests:
        stop_on_failure: true
        override:
          -
            command: js-scrutinizer-run
            on_node: 1
          -
            command: eslint-run
            on_node: 2
filter:
  paths: ["app/*", "database/factories/*", "database/seeds/*", "resources/assets/js"]
  dependency_paths:
    - bootstrap/
    - config/
    - node_modules/
    - resources/
    - routes/
    - vendor/
  excluded_paths:
    - "public/"
    - "tests/"
    - "resources/assets/js/stories/"
    - "resources/assets/js/translations/"

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 777
    runs: 1
