build:
  nodes:
    php-analysis:
      environment:
        php:
          version: "7.2"
          ini:
            memory_limit: "-1"
      tests:
        override:
          -
            command: php-scrutinizer-run
            on_node: 1
          -
            command: phpcs-run
            use_website_config: false
            on_node: 2
    js-analysis:
      environment:
        node: v10.14.2
      tests:
        override:
          -
            command: js-scrutinizer-run
            on_node: 1
          -
            command: eslint-run ./resources/assets/js
            on_node: 2
filter:
  paths: ["app/*", "database/factories/*", "database/seeds/*", "resources/assets/js"]
  dependency_paths:
    - bootstrap/
    - config/
    - node_modules/
    - resources/
    - routes/
    - vendor/
  excluded_paths:
    - "public/"
    - "tests/"
    - "resources/assets/js/stories/"
    - "resources/assets/js/translations/"

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 777
    runs: 1
