# TalentCloud code analysis (Scrutinizer) config
# .scrutinizer.yml

build:
  nodes:
    analysis:
      dependencies:
        override: true
      project_setup:
        override: true
      environment:
        php: "7.2"
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run

filter:
  paths:
    - app/
    - database/
    - routes/
    - resources/assets/js/
  excluded_paths:
    - database/migrations/
    - resources/assets/js/stories/
    - resources/assets/js/translations/
    - resources/assets/js/autocomplete.js
    - resources/assets/js/bootstrap.js
    - resources/assets/js/getpdf.js
    - resources/assets/js/jest.setup.js
    - resources/assets/js/modernizr.js
