# TalentCloud code analysis (Scrutinizer) config
# .scrutinizer.yml

build:
  nodes:
    analysis:
      environment:
        php: 7.2
        node: v12.13.1
      dependencies:
        override: true
      project_setup:
        override: true
      tests:
        override:
        - php-scrutinizer-run
        - js-scrutinizer-run
filter:
  paths:
    - app/
    - database/factories/
    - database/seeds/
    - routes/
    - resources/assets/js/
  excluded_paths:
    - database/migrations/
    - resources/assets/js/stories/
    - resources/assets/js/translations/
    - resources/assets/js/autocomplete.js
    - resources/assets/js/bootstrap.js
    - resources/assets/js/getpdf.js
    - resources/assets/js/jquery-ui.min.js
    - resources/assets/js/modernizr.js
  dependency_paths:
    - vendor/
