build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run
          - phpcs-run ./app
          - scss-lint-run

  dependencies:
    before:
      - psql --cluster 9.6/main -c 'CREATE DATABASE talentcloud WITH OWNER scrutinizer'
      - npm install
      - composer update

  environment:
    docker: true
    postgresql: true
    ruby: "2.3.1"
    node: "v6.2.0"
    php:
      version: "7.0"
      ini:
        memory_limit: "-1"
    selenium: true
    # hosts:
    #   local.dev: 127.0.0.1
    # nginx:
    #   sites:
    #     talent.local.ca:
    #       host: 'local.dev'
    #       web_root: 'public/'

  deployment:
    -
      commands:
        - heroku git:remote -a gc-talentcloud
        - git pull --rebase
        - git push -f heroku HEAD:master

filter:
  excluded_paths:
    - '*/database/*'
    - '*/node_modules/*'
    - '*/tests/*'
    - '*/vendor/*'

checks:
  php: true
  javascript: true

tools:
  external_code_coverage:
    timeout: 777
    runs: 2
  custom_commands:
    -
      scope: project
      command: vendor/bin/slack --token=https://hooks.slack.com/services/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
