build:

    environment:
        php:
            version: "7.2"
            ini:
                memory_limit: "-1"
        docker: true
        ruby: 2.5.1
        node: v10.14.2

    cache:
        directories:
            - node_modules/
            - vendor/

    nodes:
        coverage:
            tests:
                before:
                    - command: 'make docker-start'
                    - command: 'make gen-certs'
                    - command: 'make build-db'
                    - command: 'make set-perms'
                    - command: 'npm run dev'
                    - command: 'make phpunit'
                    - command: 'make jest'
                    - command: 'make docker-stop'

        analysis:
            tests:
                override:
                - php-scrutinizer-run
                - js-scrutinizer-run
                - phpcs-run --standard=ruleset.xml ./app ./routes ./database/factories ./database/seeds
                - eslint-run ./resources/assets/js/app

filter:
    paths:
        - app/
        - database/factories/
        - database/seeds/
        - resources/assets/js/app
        - routes/

    dependency_paths:
        - node_modules/
        - vendor/

    excluded_paths:
        - bootstrap/
        - config/
        - database/db/
        - database/migrations/
        - etc/
        - node_modules/
        - public/
        - report/
        - resources/
        - storage/
        - tests/
        - vendor/

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 1
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=https://hooks.slack.com/services/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
