build:
  environment:
    php:
      version: 7.2
    node: v12.13.1
  tests:
    stop_on_failure: true
    override:
      - php-scrutinizer-run
      - phpcs-run app/ database/factories/ database/seeds/ routes/ --standard=ruleset.xml
      - js-scrutinizer-run
      - eslint-run resources/assets/js/
filter:
  paths:
    - app/
    - database/factories/
    - database/seeds/
    - routes/
    - resources/assets/js/
  dependency_paths:
    - bootstrap/
    - config/
    - node_modules/
    - resources/lang/
    - resources/views/
    - vendor/
  excluded_paths:
    - etc/
    - public/
    - report/
    - tests/
    - resources/assets/js/stories/
    - resources/assets/js/translations/
    - resources/assets/js/jquery-ui.min.js
    - resources/assets/js/modernizr.js
    - resources/assets/js/getpdf.js
    - resources/assets/js/bootstrap.js
    - resources/assets/js/autocomplete.js
checks:
  php: true
  javascript: true
