build:

    dependencies:
        before:
            # composer install
            # npm install

    environment:
        php:
            version: "7.2"
            ini:
                memory_limit: "-1"
        ruby: 2.5.1
        node: v10.14.2

    cache:
        directories:
            - node_modules/
            - vendor/

filter:
    paths:
        - app/
        - database/factories/
        - database/seeds/
        - resources/assets/js/app
        - routes/

    dependency_paths:
        - node_modules/
        - vendor/

    excluded_paths:
        - bootstrap/
        - config/
        - database/db/
        - database/migrations/
        - etc/
        - public/
        - node_modules/
        - report/
        - resources/
        - storage/
        - tests/
        - vendor/

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 1
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=https://hooks.slack.com/services/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
