build:
  nodes:
    analysis:
      services:
        postgres: 9.6
      environment:
        php:
          version: "7.2"
          ini:
            memory_limit: "-1"
        node: v10.14.2
        variables:
          DB_DATABASE: scrutinizer
          DB_USERNAME: scrutinizer
          DB_PASSWORD: scrutinizer
      tests:
        stop_on_failure: true
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=ruleset.xml
          - js-scrutinizer-run
          - eslint-run resources/assets/js/
filter:
  paths: ["app/*", "database/factories/*", "database/seeds/*", "resources/assets/js"]
  dependency_paths:
    - bootstrap/
    - config/
    - node_modules/
    - resources/
    - routes/
    - vendor/
  excluded_paths:
    - "public/"
    - "tests/"
    - "resources/assets/js/stories/"
    - "resources/assets/js/translations/"

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 777
    runs: 1
