build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
                    - phpcs-run ./app

    dependencies:
        before:
            - composer install
            - npm install
            # psql --cluster 9.6/main -c 'CREATE DATABASE talentcloud WITH OWNER scrutinizer'
            - php artisan migrate

    services:
        postgres: 9.6

    environment:
        php:
            version: "7.0"
            ini:
                memory_limit: "-1"
        ruby: 2.5.1
        node: v6.5.0
        # docker: true

    cache:
        directories:
            - node_modules/
            - vendor/

filter:
    excluded_paths:
        - '*/database/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=https://hooks.slack.com/services/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
