build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
                    - phpcs-run ./app

    dependencies:
        before:
            - composer install
            - psql --cluster 9.6/main -c 'CREATE DATABASE talentcloud WITH OWNER scrutinizer'

    root_path: './'

    environment:
        # Sets up DNS entries for certain hosts
        hosts:
            local.dev: 127.0.0.1
        # Languages
        php:
            version: "7.0"
            ini:
                memory_limit: "-1"
        ruby: "2.3.1"
        node: "v6.2.0"
        # Various pre-installed services that can be configured.
        docker: true
        postgresql: true
        nginx:
            sites:
                # will add configuration file to "/etc/nginx/sites-enabled"
                tc.gccollab.ca:
                    host: 'local.dev'
                    web_root: 'public/'

        selenium: true

filter:
    excluded_paths:
        - '*/database/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=https://hooks.slack.com/services/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
