codecov:
  bot: gggrant
  branch: dev

coverage:
  precision: 1
  round: up

  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 2%
        branches: null
        only_pulls: false
    changes: no

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        #threshold: 2%
        branches: null
        only_pulls: false
        attachments: "sunburst, diff"

  parsers:
    javascript:
      enable_partials: yes

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
  branches: "*"
