version: '2'
services:
    # Web Server / Nginx
    nginx:
        image: nginx:1.13.9-alpine
        container_name: nginx
        working_dir: /var/www
        volumes_from:
            - talentcloud
        restart: always
        depends_on:
            - talentcloud
            - postgres
        ports:
            - "80:80"
            - "443:443"
    # Application / PHP-FPM
    talentcloud:
        # build: .
        image: gctcntgc/talentcloud
        container_name: talentcloud
        working_dir: /var/www
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/ssl:/etc/ssl"
            - "./:/var/www"
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=postgres"
        ports:
            - "9000:9000"
    # Database / Postgres
    postgres:
        image: postgres:9.6-alpine
        container_name: postgres
        restart: always
        volumes:
            - "pgdata:/var/lib/postgresql/data"
        environment:
            - "POSTGRES_DB=talentcloud"
            - "POSTGRES_USER=talentcloud"
            - "POSTGRES_PASSWORD=talentcloud"
        ports:
            - "5432:5432"
    # Adminer
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        links:
            - postgres
        ports:
            - "8080:8080"
volumes:
    pgdata:
