INSERT into base_content 
(base_content_type_id, base_content_key, base_content_value, base_content_locale_id) 
VALUES 
/*Evidence*/
(1,'jobApplicationPositionLabel','For the position of:',1),
(1,'jobApplicationPositionLabel','pour le poste de:',2),
(1,'applicant-evidence__skill-declaration-title','My Skill Declaration (Required)',1),
(1,'applicant-evidence__skill-declaration-title','Mon niveau de compétence (requis)',2),
(1,'applicant-evidence__expertise-radiogroup-title','My Level of Expertise',1),
(1,'applicant-evidence__expertise-radiogroup-title','Mon niveau d’expertise',2),
(1,'applicantionProgressInformationAssessment','This criteria will be assessed during the interview process.',1),
(1,'applicantionProgressInformationAssessment','Ces critères seront évalués pendant le processus d’entrevue.',2),
(1,'applicant-evidence__experience-radiogroup-title','My Years of Experience',1),
(1,'applicant-evidence__experience-radiogroup-title','Mes années d’expérience',2),
(1,'applicant-evidence__experience-and-knowledge__form-title','My Experience and Knowledge',1),
(1,'applicant-evidence__experience-and-knowledge__form-title','Mon expérience et mes connaissances',2),
(1,'applicant-evidence-done','Done!',1),
(1,'applicant-evidence-done','Tu as terminé!',2),
(1,'applicant-evidence__completion-message','This is all you need to apply. You can strengthen your claim by providing more information about your skill below.',1),
(1,'applicant-evidence__completion-message','Tu as entré tous les renseignements nécessaires pour postuler l’emploi. Tu peux maintenant renforcer ta demande d’emploi en fournissant plus de renseignements sur tes compétences ci-dessous.',2),
(1,'applicant-evidence__skill-declaration-text','What was your contribution to the project? How big was the project? How does it support your claims?',1),
(1,'applicant-evidence__skill-declaration-text','Quelle a été ta contribution à ce projet? Quelle était l’ampleur du projet? Comment ce projet appuie-t-il ta demande d’emploi?',2),
(1,'applicant-evidence__micro-reference-title','Micro-reference (Optional)',1),
(1,'applicant-evidence__micro-reference-title','Référence rapide (facultatif)',2),
(1,'applicant-evidence__appoint-reference-label','Appoint one reference that can vouch for you.',1),
(1,'applicant-evidence__appoint-reference-label','Nomme une personne-ressource qui peut recommander ta candidature.',2),
(1,'applicant-evidence__reference-name','Reference\'s Name:',1),
(1,'applicant-evidence__reference-name','Nom de la personne-ressource:',2),
(1,'applicant-evidence__reference-email','Reference\'s Email:',1),
(1,'applicant-evidence__reference-email','Courriel de la personne-ressource:',2),
(1,'applicant-evidence__reference-relationship','Your Relationship to this Reference:',1),
(1,'applicant-evidence__reference-relationship','Ta relation de travail avec cette personne :',2),
(1,'applicant-evidence__observed-from','Observed From:',1),
(1,'applicant-evidence__observed-from','Date de début de ta relation de travail avec cette personne:',2),
(1,'applicant-evidence__observed-to','Observed To:',1),
(1,'applicant-evidence__observed-to','Date de fin de votre relation de travail avec cette personne:',2),
(1,'applicant-evidence__your-experience-at-the-time','Your Experience Level at the Time:',1),
(1,'applicant-evidence__your-experience-at-the-time','Ton niveau d’expérience durant cette période:',2),
(1,'applicant-evidence__tell-us-what-you-did','Tell Us What You Did:',1),
(1,'applicant-evidence__tell-us-what-you-did','Tes fonctions durant cette période:',2),
(1,'applicant-evidence__reference-story','Provide a sentence or two about the role you played and what you\'re asking this micro-reference to validate.',1),
(1,'applicant-evidence__reference-story','En une phrase ou deux, décris le rôle que tu as joué et ce que tu demandes à cette personne-ressource de valider.',2),
(1,'applicant-evidence__sample-of-my-skill','Sample of my Skill (Optional)',1),
(1,'applicant-evidence__sample-of-my-skill','Exemple de ma compétence (facultatif)',2),
(1,'applicant-evidence__attach-work-sample','Attach an example of your work that you\'re proud of.',1),
(1,'applicant-evidence__attach-work-sample','Joins un échantillon de ton travail dont tu es fier à titre d’exemple.',2),
(1,'applicant-evidence__project-document-name','Project/Document Name:',1),
(1,'applicant-evidence__project-document-name','Titre du projet ou du document:',2),
(1,'applicant-evidence__type-of-file','Type of File:',1),
(1,'applicant-evidence__type-of-file','Type de fichier:',2),
(1,'applicant-evidence__date-created','Date Created:',1),
(1,'applicant-evidence__date-created','Date de création:',2),
(1,'applicant-evidence__link-to-evidence','Link to Evidence:',1),
(1,'applicant-evidence__link-to-evidence','Lien vers l’échantillon:',2),
(1,'applicant-evidence__story','Story:',1),
(1,'applicant-evidence__story','Description:',2),
(1,'applicant-evidence__tell-us-about-evidence','Tell us about this piece of evidence and your role in creating it.',1),
(1,'applicant-evidence__tell-us-about-evidence','Décris le projet ou le document ainsi que ton rôle dans sa réalisation.',2),
(1,'applicant-evidence__save-and-return','Save and return',1),
(1,'applicant-evidence__save-and-return','Enregistrer et retourner à la page d’accueil',2),
(1,'applicant-evidence__save-and-continue','Save and continue',1),
(1,'applicant-evidence__save-and-continue','Enregistrer et continuer ',2),
(1,'applicant-evidence__save-and-preview','Save and Preview',1),
(1,'applicant-evidence__save-and-preview','Enregistrer et voir l’aperçu',2),

/*Application Progress Tracker*/
(1,'applicationProgressMyInformation','My Information',1),
(1,'applicationProgressMyInformation','Mes renseignements',2),
(1,'applicationProgressEssentialCriteria','Essential Criteria',1),
(1,'applicationProgressEssentialCriteria','Qualifications essentielles',2),
(1,'applicationProgressNonEssentialCriteria','Non-essential Criteria',1),
(1,'applicationProgressNonEssentialCriteria','Qualifications non essentielles',2),
(1,'applicationProgressReviewMyApplication','Review My Application',1),
(1,'applicationProgressReviewMyApplication','Examiner ma demande',2),

/*Job Poster*/
(1,'jobPosterTimeRemaining','days until close',1),
(1,'jobPosterTimeRemaining','jours jusqu’à la date de clôture',2),
(1,'jobPosterApplicants','applicants so far',1),
(1,'jobPosterApplicants','candidats jusqu’à présent',2),
(1,'jobPosterIdLabel','Reference ID',1),
(1,'jobPosterIdLabel','Numéro de référence',2),
(1,'jobPosterSubnavLabel','About This Job:',1),
(1,'jobPosterSubnavLabel','À propos de l’emploi:',2),
(1,'jobPosterContentTitleBasics','Basic Information',1),
(1,'jobPosterContentTitleBasics','Renseignements généraux',2),
(1,'jobPosterSubnavItemBasics','Basic Information',1),
(1,'jobPosterSubnavItemBasics','Renseignements généraux',2),
(1,'jobPosterSubnavItemImpact','Impact',1),
(1,'jobPosterSubnavItemImpact','Contribution',2),
(1,'jobPosterSubnavItemWork','Your Work',1),
(1,'jobPosterSubnavItemWork','Travail',2),
(1,'jobPosterSubnavItemCriteria','Criteria',1),
(1,'jobPosterSubnavItemCriteria','Critères',2),
(1,'jobPosterSubnavItemCulture','Culture',1),
(1,'jobPosterSubnavItemCulture','Culture',2),
(1,'jobPosterSubnavItemApply','Apply for this Job',1),
(1,'jobPosterSubnavItemApply','Postuler cet emploi',2),
(1,'jobPosterSubnavItemApply','Apply for this Job',1),
(1,'jobPosterSubnavItemApply','Postuler cet emploi',2),
(1,'jobPosterSalaryRangeLabel','Salary range:',1),
(1,'jobPosterSalaryRangeLabel','Échelle salariale:',2),
(1,'jobPosterLanguageLabel','Language',1),
(1,'jobPosterLanguageLabel','Langue',2),
(1,'jobPosterTermLabel','Duration',1),
(1,'jobPosterTermLabel','Durée',2),
(1,'jobPosterTermValue','month',1),
(1,'jobPosterTermValue','mois',2),
(1,'jobPosterStartDateLabel','Target start date:',1),
(1,'jobPosterStartDateLabel','Date cible de début d’emploi:',2),
(1,'jobPosterClearanceLevelLabel','Security clearance level:',1),
(1,'jobPosterClearanceLevelLabel','Niveau d’autorisation de sécurité:',2),
(1,'jobPosterJobLevelLabel','Classification',1),
(1,'jobPosterJobLevelLabel','Classification',2),
(1,'jobPosterContentTitleImpact','Impact',1),
(1,'jobPosterContentTitleImpact','Contribution',2),
(1,'jobPosterContentTitleWork','Your Work',1),
(1,'jobPosterContentTitleWork','Travail',2),
(1,'jobPosterContentTitleCriteria','Criteria',1),
(1,'jobPosterContentTitleCriteria','Critères',2),
(1,'jobPosterCoreCompetenciesLabel','Need to Have',1),
(1,'jobPosterCoreCompetenciesLabel','Qualifications essentielles',2),
(1,'jobPosterDevelopingCompetenciesLabel','Nice to Have',1),
(1,'jobPosterDevelopingCompetenciesLabel','Qualifications constituant un atout',2),
(1,'jobPosterContentTitleCulture','Culture',1),
(1,'jobPosterContentTitleCulture','Culture',2),
(1,'jobPosterHiringManagerLabel','Your Manager',1),
(1,'jobPosterHiringManagerLabel','Gestionnaire',2),
(1,'jobPosterWorkEnvironmentLabel','Work Environment',1),
(1,'jobPosterWorkEnvironmentLabel','"Environnement de travail',2),
(1,'jobPosterRemoteWork_label','Remote location allowed',1),
(1,'jobPosterRemoteWork_label','Possibilité de travail depuis une région éloignée',2),
(1,'jobPosterTelework_label','Telework allowed',1),
(1,'jobPosterTelework_label','Possibilité de télétravail',2),
(1,'jobPosterFlexHours_label','Flexible hours allowed',1),
(1,'jobPosterFlexHours_label','Possibilité d’horaire flexible',2),
(1,'jobPosterTeamCultureLabel','Team Culture',1),
(1,'jobPosterTeamCultureLabel','Culture d’équipe',2),
(1,'jobPosterTeamSize_label','Team size',1),
(1,'jobPosterTeamSize_label','Taille de l’équipe ',2),
(1,'jobPosterGcDirLink_label','Meet the team in',1),
(1,'jobPosterGcDirLink_label','Rencontre l’équipe dans',2),
(1,'jobPosterOperatingContext_label','Our operating context',1),
(1,'jobPosterOperatingContext_label','Notre contexte opérationnel:',2),
(1,'jobPosterWhatWeValue_label','What we value',1),
(1,'jobPosterWhatWeValue_label','Nos valeurs:',2),
(1,'jobPosterHowWeWork_label','How we work',1),
(1,'jobPosterHowWeWork_label','Notre mode de fonctionnement:',2),
(1,'jobPosterContentTitleApply','Apply for this Job',1),
(1,'jobPosterContentTitleApply','Postuler cet emploi',2),
(1,'jobPosterLoginButton','Login and Apply',1),
(1,'jobPosterLoginButton','Ouvrir une session et postuler',2)
;