INSERT into base_content
(base_content_type_id, base_content_key, base_content_value, base_content_locale_id)
VALUES
(1,'profileBasicInfoEditTitle','Edit your basic info',1),
(1,'profileBasicInfoEditTitle','Modifier vos informations de base',2),
(1,'updateProfilePhotoTitle','Change Display Picture',1),
(1,'updateProfilePhotoTitle',"Modifier l\'image affichée",2),
(1, "updateProfilePhotoDraggableAreaLabel", "Drag New Photo", 1),
(1, "updateProfilePhotoDraggableAreaLabel", "Glisser-déposez une photo", 2),
(1, "updateProfilePhotoDraggableAreaErrorSize", "File Larger Than 2MB", 1),
(1, "updateProfilePhotoDraggableAreaErrorSize", "Fichier de plus de 2MB", 2),
(1, "updateProfilePhotoDraggableAreaErrorType", "Please Use .JPG, .JPEG, or .PNG.", 1),
(1, "updateProfilePhotoDraggableAreaErrorType", "Veuillez utiliser .JPG, .JPEG ou .PNG.", 2),
(1, "updateProfileOrCopy", "or", 1),
(1, "updateProfileOrCopy", "ou", 2),
(1, "updateProfileChoosePhotoButtonLabelSpan", "Choose File...", 1),
(1, "updateProfileChoosePhotoButtonLabelSpan", "Choisir un fichier...", 2),
(1, "updateProfileChoosePhotoButton", "User Profile Photo", 1),
(1, "updateProfileChoosePhotoButton", "Photo du profil de l'utilisateur", 2),
(1, "updateProfileChooseAltPhotoButtonLabelSpan", "Choose Another File...", 1),
(1, "updateProfileChooseAltPhotoButtonLabelSpan", "Choisissez un autre fichier...", 2),
(1, "updateProfileChooseAltPhotoButton", "User Profile Photo", 1),
(1, "updateProfileChooseAltPhotoButton", "Photo du profil de l'utilisateur", 2),
(1, "updateProfilePhotoCancelButton", "Remove Photo", 1),
(1, "updateProfilePhotoCancelButton", "Retirer la photo", 2),
(1, "updateProfileApplicantProfileFormFirstNameLabelSpan", "First Name:", 1),
(1, "updateProfileApplicantProfileFormFirstNameLabelSpan", "Prénom:", 2),
(1, "profileEditFirstName", "profileEditFirstName", 1),
(1, "profileEditFirstName", "profilModifierLePrénom", 2),
(1, "updateProfileApplicantProfileFormLastNameLabelSpan", "Last Name:", 1),
(1, "updateProfileApplicantProfileFormLastNameLabelSpan", "Nom de famille:", 2),
(1, "profileEditLastName", "profileEditLastName", 1),
(1, "profileEditLastName", "profilModifierLeNomDeFamille", 2),
(1, "updateProfileApplicantProfileFormTaglineLabelSpan", "Tagline", 1),
(1, "updateProfileApplicantProfileFormTaglineLabelSpan", "Slogan", 2),
(1, "profileEditTagline", "profileEditTagline", 1),
(1, "profileEditTagline", "profileModifierLeSlogan", 2),
(1, "updateProfileApplicantProfileFormTwitterLabelSpan", "Twitter Handle:", 1),
(1, "updateProfileApplicantProfileFormTwitterLabelSpan", "Nom d'utilisateur de Twitter", 2),
(1, "profileEditTwitter", "profileEditTwitter", 1),
(1, "profileEditTwitter", "profilModifierTwitter", 2),
(1, "updateProfileApplicantProfileFormLinkedinLabelSpan", "LinkedIn Profile Address:", 1),
(1, "updateProfileApplicantProfileFormLinkedinLabelSpan", "Adresse du profil LinkedIn:", 2),
(1, "profileEditLinkedin", "profileEditLinkedin", 1),
(1, "profileEditLinkedin", "profilModifierLinkedin", 2),
(1, "profileBasicInfoEditCancel", "Cancel", 1),
(1, "profileBasicInfoEditCancel", "Annuler", 2),
(1, "profileBasicInfoEditSave", "Save", 1),
(1, "profileBasicInfoEditSave", "Enregistrer", 2),
(1, "loginFormTitle", "Login to TalentCloud", 1),
(1, "loginFormTitle", "Connectez-vous à TalentCloud", 2),
(1, "loginModalCopySpan", "Welcome to TalentCloud! ", 1),
(1, "loginModalCopySpan", "Bienvenue à TalentCloud! ", 2),
(1, "switchToRegister", "Don't have an account? Click here to register.", 1),
(1, "switchToRegister", "Vous n'avez pas de compte? Cliquez ici pour vous inscrire.", 2),
(1, "loginModalEmailLabelSpan", "Your Email:", 1),
(1, "loginModalEmailLabelSpan", "Votre email:", 2),
(1, "login_email", "login_email", 1),
(1, "login_email", "connecter_avec_email", 2),
(1, "loginModalPasswordLabelSpan", "Your Password:", 1),
(1, "loginModalPasswordLabelSpan", "Votre mot de passe:", 2),
(1, "login_password", "login_password", 1),
(1, "login_password", "mot_de_passe", 2),
(1, "loginFormCancelBtn", "Cancel", 1),
(1, "loginFormCancelBtn", "Annuler", 2),
(1, "loginFormLoginBtn", "Login", 1),
(1, "loginFormLoginBtn", "S'identifier", 2),
(1, "registerFormTitle", "Register for TalentCloud", 1),
(1, "registerFormTitle", "Inscrivez-vous à TalentCloud", 2),
(1, "profileAboutMeEditTitle", "Edit Your \"About Me\" Information", 1),
(1, "profileAboutMeEditTitle", "Modifier vos informations \"À propos de moi\"", 2),
(1, "updateAboutTextareaLabelSpan", "About Me:", 1),
(1, "updateAboutTextareaLabelSpan", "À propos de moi:", 2),
(1, "profileEditAboutMe", "profileEditAboutMe", 1),
(1, "profileEditAboutMe", "profilModifierÀProposDeMoi", 2),
(1, "profileAboutMeEditCancel", "Cancel", 1),
(1, "profileAboutMeEditCancel", "Annuler", 2),
(1, "profileAboutMeEditSave", "Save", 1),
(1, "profileAboutMeEditSave", "Enregistrer", 2)
;
