INSERT into base_content
(base_content_type_id, base_content_key, base_content_value, base_content_locale_id)
VALUES
(1,'profileBasicInfoEditTitle','Edit your basic info',1),
(1,'profileBasicInfoEditTitle','Modifier vos informations de base',2),
(1,'updateProfilePhotoTitle','Change Display Picture',1),
(1,'updateProfilePhotoTitle',"Modifier l\'image affichée",2),
(1, "updateProfilePhotoDraggableAreaLabel", "Drag New Photo", 1),
(1, "updateProfilePhotoDraggableAreaLabel", "Glisser-déposez une photo", 2),
(1, "updateProfilePhotoDraggableAreaErrorSize", "File Larger Than 2MB", 1),
(1, "updateProfilePhotoDraggableAreaErrorSize", "Fichier de plus de 2MB", 2),
(1, "updateProfilePhotoDraggableAreaErrorType", "Please Use .JPG, .JPEG, or .PNG.", 1),
(1, "updateProfilePhotoDraggableAreaErrorType", "Veuillez utiliser .JPG, .JPEG ou .PNG.", 2),
(1, "updateProfileOrCopy", "or", 1),
(1, "updateProfileOrCopy", "ou", 2),
(1, "updateProfileChoosePhotoButtonLabelSpan", "Choose File...", 1),
(1, "updateProfileChoosePhotoButtonLabelSpan", "Choisir un fichier...", 2),
(1, "updateProfileChoosePhotoButton", "User Profile Photo", 1),
(1, "updateProfileChoosePhotoButton", "Photo du profil de l'utilisateur", 2),
(1, "updateProfileChooseAltPhotoButtonLabelSpan", "Choose Another File...", 1),
(1, "updateProfileChooseAltPhotoButtonLabelSpan", "Choisissez un autre fichier...", 2),
(1, "updateProfileChooseAltPhotoButton", "User Profile Photo", 1),
(1, "updateProfileChooseAltPhotoButton", "Photo du profil de l'utilisateur", 2),
(1, "updateProfilePhotoCancelButton", "Remove Photo", 1),
(1, "updateProfilePhotoCancelButton", "Retirer la photo", 2),
(1, "updateProfileApplicantProfileFormFirstNameLabelSpan", "First Name:", 1),
(1, "updateProfileApplicantProfileFormFirstNameLabelSpan", "Prénom:", 2),
(1, "profileEditFirstName", "profileEditFirstName", 1),
(1, "profileEditFirstName", "profilModifierLePrénom", 2),
(1, "updateProfileApplicantProfileFormLastNameLabelSpan", "Last Name:", 1),
(1, "updateProfileApplicantProfileFormLastNameLabelSpan", "Nom de famille:", 2),
(1, "profileEditLastName", "profileEditLastName", 1),
(1, "profileEditLastName", "profilModifierLeNomDeFamille", 2),
(1, "updateProfileApplicantProfileFormTaglineLabelSpan", "Tagline", 1),
(1, "updateProfileApplicantProfileFormTaglineLabelSpan", "Slogan", 2),
(1, "profileEditTagline", "profileEditTagline", 1),
(1, "profileEditTagline", "profileModifierLeSlogan", 2),
(1, "updateProfileApplicantProfileFormTwitterLabelSpan", "Twitter Handle:", 1),
(1, "updateProfileApplicantProfileFormTwitterLabelSpan", "Nom d'utilisateur de Twitter", 2),
(1, "profileEditTwitter", "profileEditTwitter", 1),
(1, "profileEditTwitter", "profilModifierTwitter", 2),
(1, "updateProfileApplicantProfileFormLinkedinLabelSpan", "LinkedIn Profile Address:", 1),
(1, "updateProfileApplicantProfileFormLinkedinLabelSpan", "Adresse du profil LinkedIn:", 2),
(1, "profileEditLinkedin", "profileEditLinkedin", 1),
(1, "profileEditLinkedin", "profilModifierLinkedin", 2),
(1, "profileBasicInfoEditCancel", "Cancel", 1),
(1, "profileBasicInfoEditCancel", "Annuler", 2),
(1, "profileBasicInfoEditSave", "Save", 1),
(1, "profileBasicInfoEditSave", "Enregistrer", 2)
;
