INSERT into base_content
(base_content_type_id, base_content_key, base_content_value, base_content_locale_id)
VALUES
/* Application Preview */
(1,'years','Years',1),
(1,'years','Années',2),
(1,'status','Status',1),
(1,'status','Status (FR)',2),
(1,'applicationPositionLabel', 'for the position of',1),
(1,'applicationPositionLabel', 'pour le position de',2),
(1,'essentialCriteria','Essential Criteria',1),
(1,'essentialCriteria','Essential Criteria (FR)',2),
(1,'assetCriteria','Asset Criteria',1),
(1,'assetCriteria','Asset Criteria (FR)',2),
(1,'microReference','Micro-Reference',1),
(1,'microReference','Micro-Reference (FR)',2),
(1,'skillSample','Skill Sample',1),
(1,'skillSample','Skill Sample (FR)',2),
(1,'editApplication','Edit Application',1),
(1,'editApplication','Edit Application (FR)',2),
(1,'applicationPreviewProfilePhotoTitle','My profile photo.',1),
(1,'applicationPreviewProfilePhotoTitle','Mon photo profile.',2),
(1,'applicationPreviewProfileAlert','Remember that hiring managers can view your full profile when you submit an application. By filling out your profile you increase your chances of getting hired.',1),
(1,'applicationPreviewProfileAlert','(TRANSLATION NEEDED) Remember that hiring managers can view your full profile when you submit an application. By filling out your profile you increase your chances of getting hired.',2),
(1,'applicationPreviewDeclarationStoryTitle','Experience &amp; Knowledge',1),
(1,'applicationPreviewDeclarationStoryTitle','(TRANSLATION NEEDED) Experience &amp; Knowledge',2),
(1,'applicationPreviewReferenceMissing','No reference was provided.',1),
(1,'applicationPreviewReferenceMissing','(TRANSLATION NEEDED) No reference was provided.',2),
(1,'applicationPreviewSkillSampleStoryLabel','Contribution',1),
(1,'applicationPreviewSkillSampleStoryLabel','(TRANSLATION NEEDED) Contribution',2),
(1,'applicationPreviewSkillSampleLink','View Evidence',1),
(1,'applicationPreviewSkillSampleLink','(TRANSLATION NEEDED)View Evidence',2),
(1,'applicationPreviewSkillSampleMissing','No skill sample provided.',1),
(1,'applicationPreviewSkillSampleMissing','(TRANSLATION NEEDED) No skill sample provided.',2),
(1,'jobPosterTeamNarrativeText_label','Things to Know',1),
(1,'jobPosterTeamNarrativeText_label','À savoir',2),
(1,'jobPosterBackButtonText','Back to Job Poster',1),
(1,'jobPosterBackButtonText','Retour à l\'affiche de l\'emploi',2)
;
