/* eslint camelcase: "off", @typescript-eslint/camelcase: "off" */
import { Application } from "../models/types";

export const fakeApplication1 = (): Application => ({
  id: 1,
  job_poster_id: 1,
  application_status_id: 1,
  citizenship_declaration_id: 1,
  veteran_status_id: 1,
  preferred_language_id: 1,
  applicant_id: 1,
  applicant_snapshot_id: 1,
  submission_signature: "signed",
  submission_date: "2020-01-01",
  experience_saved: true,
  created_at: new Date("2020-01-01"),
  updated_at: new Date("2020-01-01"),
  veteran_status: {
    id: 1,
    name: "none",
  },
  citizenship_declaration: {
    id: 1,
    name: "citizen",
  },
  applicant: {
    id: 1,
    personal_website: "www.somesite.com",
    tagline: "Tagline",
    twitter_username: "someperson",
    linkedin_url: "linkedin.com/someperson",
    user_id: 1,
    created_at: new Date("2019-12-31"),
    updated_at: new Date("2019-12-31"),
    user: {
      id: 1,
      first_name: "Frankie",
      last_name: "Lambda",
      full_name: "Frankie Lambda",
      email: "frankie.lambda@canada.ca",
      is_confirmed: true,
      user_role_id: 1,
      created_at: new Date("2019-12-31"),
      updated_at: new Date("2019-12-31"),
      is_priority: false,
      not_in_gov: false,
      gov_email: "frankie.lambda@canada.ca",
      department_id: 1,
      user_role: {
        id: 1,
        key: "basic",
        created_at: new Date("2019-01-01"),
        updated_at: new Date("2019-01-01"),
        name: {
          en: "Applicant",
          fr: "Applicant",
        },
      },
    },
  },
  application_review: undefined,
  meets_essential_criteria: true,
});

export const fakeApplication2 = (): Application => ({
  id: 2,
  job_poster_id: 1,
  application_status_id: 1,
  citizenship_declaration_id: 1,
  veteran_status_id: 1,
  preferred_language_id: 1,
  applicant_id: 2,
  applicant_snapshot_id: 2,
  submission_signature: "signed",
  submission_date: "2020-01-01",
  experience_saved: true,
  created_at: new Date("2020-01-01"),
  updated_at: new Date("2020-01-01"),
  veteran_status: {
    id: 1,
    name: "none",
  },
  citizenship_declaration: {
    id: 1,
    name: "citizen",
  },
  applicant: {
    id: 2,
    personal_website: "www.somesite.com",
    tagline: "Tagline",
    twitter_username: "someperson",
    linkedin_url: "linkedin.com/someperson",
    user_id: 2,
    created_at: new Date("2019-12-31"),
    updated_at: new Date("2019-12-31"),
    user: {
      id: 2,
      first_name: "Mervin",
      last_name: "Greenfelder",
      full_name: "Mervin Greenfelder",
      email: "mervin.greenfelder@canada.ca",
      is_confirmed: true,
      user_role_id: 1,
      created_at: new Date("2019-12-31"),
      updated_at: new Date("2019-12-31"),
      is_priority: false,
      not_in_gov: false,
      gov_email: "mervin.greenfelder@canada.ca",
      department_id: 2,
      user_role: {
        id: 1,
        key: "basic",
        created_at: new Date("2019-01-01"),
        updated_at: new Date("2019-01-01"),
        name: {
          en: "Applicant",
          fr: "Applicant",
        },
      },
    },
  },
  application_review: {
    id: 1,
    review_status_id: 6,
    notes: "Here's some notes.",
    created_at: new Date("2020-01-02"),
    updated_at: new Date("2020-01-02"),
    review_status: {
      id: 6,
      name: "assessment_required",
    },
  },
  meets_essential_criteria: true,
});

export const fakeApplication3 = (): Application => ({
  id: 3,
  job_poster_id: 1,
  application_status_id: 1,
  citizenship_declaration_id: 1,
  veteran_status_id: 1,
  preferred_language_id: 1,
  applicant_id: 3,
  applicant_snapshot_id: 2,
  submission_signature: "signed",
  submission_date: "2020-01-01",
  experience_saved: true,
  created_at: new Date("2020-01-01"),
  updated_at: new Date("2020-01-01"),
  veteran_status: {
    id: 1,
    name: "none",
  },
  citizenship_declaration: {
    id: 1,
    name: "citizen",
  },
  applicant: {
    id: 3,
    personal_website: "www.somesite.com",
    tagline: "Tagline",
    twitter_username: "someperson",
    linkedin_url: "linkedin.com/someperson",
    user_id: 3,
    created_at: new Date("2019-12-31"),
    updated_at: new Date("2019-12-31"),
    user: {
      id: 3,
      first_name: "Ledner",
      last_name: "Rudy",
      full_name: "Ledner Rudy",
      email: "ledner.rudy@canada.ca",
      is_confirmed: true,
      user_role_id: 1,
      created_at: new Date("2019-12-31"),
      updated_at: new Date("2019-12-31"),
      is_priority: false,
      not_in_gov: false,
      gov_email: "ledner.rudy@canada.ca",
      department_id: 2,
      user_role: {
        id: 1,
        key: "basic",
        created_at: new Date("2019-01-01"),
        updated_at: new Date("2019-01-01"),
        name: {
          en: "Applicant",
          fr: "Applicant",
        },
      },
    },
  },
  application_review: {
    id: 2,
    review_status_id: 4,
    notes: "Here's some notes.",
    created_at: new Date("2020-01-02"),
    updated_at: new Date("2020-01-02"),
    review_status: {
      id: 4,
      name: "ready_for_reference",
    },
  },
  meets_essential_criteria: true,
});

const fakeApplications = (): Application[] => [
  fakeApplication1(),
  fakeApplication2(),
  fakeApplication3(),
];

export default fakeApplications;
