<?php

/**
 * Defines the database server host name.
 */
define('SECRET', "Jal4nkIV1uWGodUuiB8Peb6bsIbVsfgn3mvHwMZ7FENsPK8RgzA7Ldo6ck7ngMV");

define('ISSUER', 'talentcloud.localhost');

define("OPENID_URI","https://account.gccollab.ca/openid");

define("AUTH_URI","/authorize");

define("REGISTER_URI","https://account.gccollab.ca/register");

define("CLIENT_ID", "800830");

define("CLIENT_SECRET","68eb6645ec8e59ef31633b80e8b777ebb62fbeeec3d127fc822b4fcc");

define("REDIRECT_URI", "https://tc.gccollab.ca/");

define("REDIRECT_URI_ADMIN", "https://tc.gccollab.ca/admin");

define("URL_RESPONSE_TYPES", "code");

define("SCOPE", "openid+profile+email");


?>