<?php

/**
 * Defines the database server host name.
 */
define('HOST', "127.0.0.1");
//define('HOST', "f.gccollab.ca");
/**
 * Defines the database server database name.
 */
define('DBNAME', "talentcloud");
/**
 * Defines the database password.
 */
define('USERNAME', "talentcloud");
//define('USERNAME', "TalentCloud");
/**
 * Defines the database username.
 */
define('PASSWORD', "talentcloud");
//define('PASSWORD', "TalentCloud123!");
?>