<?php

/**
 * Defines the email user and server configuration details.
 */
define('FROM_NAME', "Talent Cloud-nuage de talents");

define('FROM_EMAIL', "Talent.Cloud-nuage.de.talents@tbs-sct.gc.ca");

/**
 * SMTP server address or ip
 */
define('SMTP_HOST', "127.0.0.1");

/**
 * defines the smtp port
 * switch to 465 or other port if SSL/TLS will be used
 */
define('SMTP_PORT', "25");

/**
 * use ssl flag for smtp
 */
define('USE_SSL',false);

/**
 * Defines the database password.
 */
define('SMTP_USERNAME', "talentcloud");

/**
 * Defines the database username.
 */
define('SMTP_PASSWORD', "talentcloud");
//define('SMTP_PASSWORD', "TalentCloud123!");
?>