name: Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      postgres:
         image: postgres:9.6-alpine
         options: --name=postgres
         env:
           POSTGRES_DB: talentcloud
           POSTGRES_USER: talentcloud
           POSTGRES_PASSWORD: talentcloud
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.travis', '.env');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      uses: php-actions/composer@v4
      with:
        command: install --no-interaction --prefer-dist --no-progress --no-suggest
        php_version: 7.2
        composer_version: 1
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage
    - name: Generate certificates
      run: make gen-certs
    - name: Create Laravel storage symlink
      run: php artisan storage:link
    - name: Setup database
      run: docker exec -d postgres psql -c 'create database testing with owner talentcloud;' -U talentcloud
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-clover=report/phpunit/coverage.xml --log-junit=report/phpunit/junit.phpunit.xml
      env:
        DB_PORT: 5432
        DB_HOST: postgres
    - name: Upload reports to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: report/phpunit/coverage.xml,report/phpunit/junit.phpunit.xml
        fail_ci_if_error: true
       
       
